"""
目录结构迁移脚本 - 将扁平文件转为「一工具/插件一文件夹」结构

迁移规则:
  工具: src/tools/builtin/{name}.py → src/tools/builtin/{name}/tool.py + __init__.py
  插件: src/plugins/{layer}/{name}.py → src/plugins/{layer}/{name}/plugin.py + __init__.py

用法:
  python scripts/migrate_structure.py --dry-run   # 预览变更
  python scripts/migrate_structure.py --execute    # 执行迁移
"""

import os
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(r"d:\Jianguoyun\Agent os")
SRC = ROOT / "src"

DRY_RUN = "--dry-run" in sys.argv
EXECUTE = "--execute" in sys.argv

if not DRY_RUN and not EXECUTE:
    print("请指定 --dry-run 或 --execute")
    sys.exit(1)


def log(action: str, src: str, dst: str | None = None) -> None:
    prefix = "[DRY-RUN]" if DRY_RUN else "[EXECUTE]"
    if dst:
        print(f"  {prefix} {action}: {src} → {dst}")
    else:
        print(f"  {prefix} {action}: {src}")


def extract_exports(content: str) -> list[str]:
    """从 Python 文件中提取 __all__ 或顶层 class/function 名称"""
    names = []
    all_match = re.search(r"__all__\s*=\s*\[(.*?)\]", content, re.DOTALL)
    if all_match:
        items = all_match.group(1)
        names = re.findall(r'"(\w+)"', items)
        if not names:
            names = re.findall(r"'(\w+)'", items)
    if not names:
        for m in re.finditer(r"^class\s+(\w+)", content, re.MULTILINE):
            names.append(m.group(1))
    return names


def create_init_py(folder: Path, exports: list[str], original_module: str) -> None:
    """创建 __init__.py，从 tool.py/plugin.py 重导出"""
    if not exports:
        exports = ["*"]
    lines = [f'"""Auto-generated by migrate_structure.py."""\n\n']
    if exports == ["*"]:
        lines.append(f"from .tool import *\n")
    else:
        for name in exports:
            lines.append(f"from .tool import {name}\n")
    lines.append("\n")
    if exports != ["*"]:
        lines.append(f"__all__ = {repr(exports)}\n")
    content = "".join(lines)
    if EXECUTE:
        folder.mkdir(parents=True, exist_ok=True)
        (folder / "__init__.py").write_text(content, encoding="utf-8")
    log("CREATE", str(folder / "__init__.py"))


def migrate_single_file(
    src_file: Path,
    dest_dir: Path,
    new_name: str = "tool.py",
) -> None:
    """将单文件迁移到文件夹结构"""
    if not src_file.exists():
        print(f"  [SKIP] 文件不存在: {src_file}")
        return

    content = src_file.read_text(encoding="utf-8")
    exports = extract_exports(content)

    if EXECUTE:
        dest_dir.mkdir(parents=True, exist_ok=True)
        dest_file = dest_dir / new_name
        shutil.copy2(str(src_file), str(dest_file))

    log("MIGRATE", str(src_file), str(dest_dir / new_name))
    create_init_py(dest_dir, exports, "")


def migrate_tools() -> None:
    """迁移 src/tools/builtin/ 下的扁平工具文件"""
    print("\n=== Phase 1: 迁移工具 (src/tools/builtin/) ===\n")
    builtin_dir = SRC / "tools" / "builtin"

    skip_names = {
        "__init__.py", "base.py", "builtin.md", "all_tool_names.txt",
    }
    skip_prefixes = {"test_"}

    existing_dirs = {
        "bash", "evaluators", "shared", "capability_adapters", "playwright_test",
    }

    test_files = []

    for src_file in sorted(builtin_dir.glob("*.py")):
        name = src_file.name
        stem = src_file.stem

        if name in skip_names:
            log("SKIP (base)", name)
            continue

        if stem in existing_dirs:
            log("SKIP (existing dir)", name)
            continue

        if any(name.startswith(p) for p in skip_prefixes):
            test_files.append(src_file)
            continue

        migrate_single_file(
            src_file=src_file,
            dest_dir=builtin_dir / stem,
            new_name="tool.py",
        )

    if test_files:
        print(f"\n  --- 发现 {len(test_files)} 个测试文件（应移到 tests/tools/）---")
        for tf in test_files:
            log("TODO-MOVE-TEST", str(tf), f"tests/tools/builtin/{tf.name}")


def migrate_plugins() -> None:
    """迁移 src/plugins/ 下的插件文件"""
    print("\n=== Phase 2: 迁移插件 (src/plugins/) ===\n")

    layers = {
        "input": SRC / "plugins" / "input",
        "output": SRC / "plugins" / "output",
        "core": SRC / "plugins" / "core",
    }

    skip_names = {"__init__.py"}

    for layer_name, layer_dir in layers.items():
        if not layer_dir.exists():
            print(f"  [SKIP] 目录不存在: {layer_dir}")
            continue

        print(f"  --- {layer_name}/ ({layer_dir}) ---")

        for src_file in sorted(layer_dir.glob("*.py")):
            name = src_file.name
            stem = src_file.stem

            if name in skip_names:
                log("SKIP (init)", name)
                continue

            migrate_single_file(
                src_file=src_file,
                dest_dir=layer_dir / stem,
                new_name="plugin.py",
            )


def update_auto_loader() -> None:
    """更新 auto_loader.py 的扫描逻辑"""
    print("\n=== Phase 1c: 更新 auto_loader.py ===\n")

    loader_file = SRC / "tools" / "auto_loader.py"
    if not loader_file.exists():
        print("  [SKIP] auto_loader.py 不存在")
        return

    content = loader_file.read_text(encoding="utf-8")

    old_pattern = 'for py_file in self.TOOL_CODE_DIR.rglob("*.py"):'
    new_pattern = 'for entry in self.TOOL_CODE_DIR.iterdir():\n            if entry.is_dir() and not entry.name.startswith("_"):\n                tool_file = entry / "tool.py"\n                if tool_file.exists():\n                    py_file = tool_file\n                else:\n                    continue\n            elif entry.is_file() and entry.suffix == ".py" and not entry.name.startswith("_"):\n                py_file = entry\n            else:\n                continue'

    if old_pattern in content:
        if EXECUTE:
            content = content.replace(old_pattern, new_pattern, 1)
            loader_file.write_text(content, encoding="utf-8")
        log("UPDATE", str(loader_file), "扫描逻辑: 支持 {name}/tool.py 结构")
    else:
        log("SKIP", "auto_loader.py 已更新或不包含旧模式")


def update_builtin_init() -> None:
    """更新 builtin/__init__.py 的导入路径"""
    print("\n=== Phase 1d: 更新 builtin/__init__.py ===\n")

    init_file = SRC / "tools" / "builtin" / "__init__.py"
    if not init_file.exists():
        print("  [SKIP] __init__.py 不存在")
        return

    content = init_file.read_text(encoding="utf-8")

    replacements = {
        "from .memory import MemoryTool": "from .memory.tool import MemoryTool",
        "from .task import TaskTool": "from .task.tool import TaskTool",
        "from .task_evaluate import TaskEvaluateTool": "from .task_evaluate.tool import TaskEvaluateTool",
        "from .task_submit import TaskSubmitTool": "from .task_submit.tool import TaskSubmitTool",
        "from .bash import BashTool": "from .bash import BashTool",
        "from .enhanced_search import EnhancedSearchTool": "from .enhanced_search.tool import EnhancedSearchTool",
        "from .file_read import FileReadTool": "from .file_read.tool import FileReadTool",
        "from .file_write import FileWriteTool": "from .file_write.tool import FileWriteTool",
        "from .lsp_tools import LSPTools": "from .lsp_tools.tool import LSPTools",
        "from .resource_merge import ResourceMergeTool": "from .resource_merge.tool import ResourceMergeTool",
        "from .resource_search import ResourceSearchTool": "from .resource_search.tool import ResourceSearchTool",
        "from .web import WebTool": "from .web.tool import WebTool",
        "from .web_search_mcp import WebSearchMCPTool": "from .web_search_mcp.tool import WebSearchMCPTool",
        "from .human_interaction import HumanInteractionTool": "from .human_interaction.tool import HumanInteractionTool",
    }

    changed = False
    for old, new in replacements.items():
        if old in content:
            content = content.replace(old, new)
            changed = True
            log("REPLACE", old, new)

    if changed and EXECUTE:
        init_file.write_text(content, encoding="utf-8")


def update_plugin_inits() -> None:
    """更新 plugins/ 各层 __init__.py 的导入路径"""
    print("\n=== Phase 2d: 更新 plugins/ __init__.py ===\n")

    layers = {
        "input": SRC / "plugins" / "input" / "__init__.py",
        "output": SRC / "plugins" / "output" / "__init__.py",
    }

    for layer_name, init_file in layers.items():
        if not init_file.exists():
            print(f"  [SKIP] {init_file} 不存在")
            continue

        content = init_file.read_text(encoding="utf-8")

        pattern = rf"from plugins\.{layer_name}\.(\w+) import"
        matches = re.findall(pattern, content)

        if not matches:
            print(f"  [SKIP] {layer_name}/__init__.py 无需更新")
            continue

        for module_name in matches:
            old = f"from plugins.{layer_name}.{module_name} import"
            new = f"from plugins.{layer_name}.{module_name}.plugin import"
            if old in content:
                content = content.replace(old, new)
                log("REPLACE", old, new)

        if EXECUTE:
            init_file.write_text(content, encoding="utf-8")

    plugins_init = SRC / "plugins" / "__init__.py"
    if plugins_init.exists():
        content = plugins_init.read_text(encoding="utf-8")
        changed = False
        for layer_name in ["input", "output"]:
            pattern = rf"from plugins\.{layer_name}\.(\w+) import"
            for match in re.finditer(pattern, content):
                module_name = match.group(1)
                old = f"from plugins.{layer_name}.{module_name} import"
                new = f"from plugins.{layer_name}.{module_name}.plugin import"
                if old in content:
                    content = content.replace(old, new)
                    changed = True
                    log("REPLACE", old, new)
        if changed and EXECUTE:
            plugins_init.write_text(content, encoding="utf-8")


def cleanup_old_files() -> None:
    """删除已迁移的原始扁平文件"""
    print("\n=== Phase 1e/2e: 清理旧文件 ===\n")

    if DRY_RUN:
        print("  [DRY-RUN] 跳过清理（仅预览模式）")
        return

    builtin_dir = SRC / "tools" / "builtin"
    skip_names = {"__init__.py", "base.py", "builtin.md", "all_tool_names.txt"}
    existing_dirs = {"bash", "evaluators", "shared", "capability_adapters", "playwright_test",
                     "__pycache__"}

    for src_file in sorted(builtin_dir.iterdir()):
        if src_file.is_dir():
            if src_file.name not in existing_dirs and not src_file.name.startswith("_"):
                pass
            continue
        if src_file.name in skip_names:
            continue
        if src_file.suffix == ".py" and not src_file.name.startswith("test_"):
            stem = src_file.stem
            new_dir = builtin_dir / stem
            if new_dir.is_dir() and (new_dir / "tool.py").exists():
                log("DELETE", str(src_file))
                src_file.unlink()

    for layer_name in ["input", "output"]:
        layer_dir = SRC / "plugins" / layer_name
        if not layer_dir.exists():
            continue
        for src_file in sorted(layer_dir.iterdir()):
            if src_file.is_dir():
                continue
            if src_file.name == "__init__.py":
                continue
            if src_file.suffix == ".py":
                stem = src_file.stem
                new_dir = layer_dir / stem
                if new_dir.is_dir() and (new_dir / "plugin.py").exists():
                    log("DELETE", str(src_file))
                    src_file.unlink()


def main() -> None:
    mode = "DRY-RUN（预览）" if DRY_RUN else "EXECUTE（执行）"
    print(f"=== 目录结构迁移脚本 [{mode}] ===")

    migrate_tools()
    migrate_plugins()
    update_auto_loader()
    update_builtin_init()
    update_plugin_inits()
    cleanup_old_files()

    print(f"\n=== 迁移完成 [{mode}] ===")


if __name__ == "__main__":
    main()
